// Package docgen generates Markdown or self-contained HTML documentation for
// a collection. Used by `senda docs` (and `senda run --docs`).
package docgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"regexp"
	"strings"

	"senda/internal/model"
	"senda/internal/store"
)

// Format controls the output format.
type Format string

const (
	FormatMarkdown Format = "md"
	FormatHTML     Format = "html"
)

// GenerateMarkdown produces a Markdown API reference for all requests under
// collPath (optionally filtered to subPath). Each request becomes a section.
func GenerateMarkdown(collPath, subPath string) (string, error) {
	reqs, err := loadRequests(collPath, subPath)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	coll, _ := store.OpenCollection(collPath)
	b.WriteString("# " + coll.Name + " API Reference\n\n")
	b.WriteString("*Generated by senda*\n\n---\n\n")
	for _, req := range reqs {
		writeMarkdownRequest(&b, req)
	}
	return b.String(), nil
}

// GenerateHTML produces a self-contained single-file HTML page for the
// collection.
func GenerateHTML(collPath, subPath string) (string, error) {
	md, err := GenerateMarkdown(collPath, subPath)
	if err != nil {
		return "", err
	}
	return wrapHTML(md), nil
}

// loadRequests reads all request files under target.
func loadRequests(collPath, subPath string) ([]model.Request, error) {
	target := collPath
	if subPath != "" {
		target = subPath
	}
	paths, err := store.ListRequests(target)
	if err != nil {
		return nil, err
	}
	reqs := make([]model.Request, 0, len(paths))
	for _, p := range paths {
		r, err := store.ReadRequest(p)
		if err != nil {
			continue
		}
		reqs = append(reqs, r)
	}
	return reqs, nil
}

func writeMarkdownRequest(b *strings.Builder, r model.Request) {
	method := r.Method
	if method == "" {
		method = "GET"
	}
	name := r.Name
	if name == "" {
		name = r.URL
	}
	fmt.Fprintf(b, "## %s\n\n", name)
	fmt.Fprintf(b, "`%s %s`\n\n", method, r.URL)

	if r.Docs != "" {
		b.WriteString(r.Docs + "\n\n")
	}

	if len(r.Params) > 0 {
		b.WriteString("### Query Parameters\n\n")
		b.WriteString("| Name | Value | Enabled |\n|---|---|---|\n")
		for _, kv := range r.Params {
			if kv.Enabled {
				fmt.Fprintf(b, "| `%s` | `%s` | ✓ |\n", kv.Key, kv.Value)
			}
		}
		b.WriteString("\n")
	}

	if len(r.Headers) > 0 {
		b.WriteString("### Headers\n\n")
		b.WriteString("| Name | Value |\n|---|---|\n")
		for _, kv := range r.Headers {
			if kv.Enabled {
				fmt.Fprintf(b, "| `%s` | `%s` |\n", kv.Key, kv.Value)
			}
		}
		b.WriteString("\n")
	}

	if r.Body.Type != "" && r.Body.Type != model.BodyNone {
		b.WriteString("### Body\n\n")
		fmt.Fprintf(b, "*Type: %s*\n\n", r.Body.Type)
		if r.Body.Raw != "" {
			lang := "text"
			if r.Body.Type == model.BodyJSON {
				lang = "json"
			} else if r.Body.Type == model.BodyGraphQL {
				lang = "graphql"
			}
			fmt.Fprintf(b, "```%s\n%s\n```\n\n", lang, prettyJSON(r.Body.Raw, r.Body.Type))
		}
	}

	if len(r.Asserts) > 0 {
		b.WriteString("### Assertions\n\n")
		b.WriteString("| Target | Op | Expected |\n|---|---|---|\n")
		for _, a := range r.Asserts {
			if a.Enabled {
				fmt.Fprintf(b, "| `%s` | %s | `%s` |\n", a.Target, a.Op, a.Value)
			}
		}
		b.WriteString("\n")
	}

	if r.ResponseSchema != "" {
		b.WriteString("### Response Schema\n\n")
		fmt.Fprintf(b, "```json\n%s\n```\n\n", prettyJSON(r.ResponseSchema, model.BodyJSON))
	}

	b.WriteString("---\n\n")
}

func prettyJSON(s string, t model.BodyType) string {
	if t != model.BodyJSON {
		return s
	}
	var v any
	if err := json.Unmarshal([]byte(s), &v); err != nil {
		return s
	}
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return s
	}
	return string(out)
}

func wrapHTML(md string) string {
	var buf bytes.Buffer
	buf.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>API Reference</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:900px;margin:0 auto;padding:2rem;color:#222;background:#fff}
h1{border-bottom:2px solid #eee;padding-bottom:.5rem}
h2{margin-top:2rem;padding:.3rem .6rem;background:#f6f8fa;border-left:4px solid #0066cc}
h3{color:#555;font-size:1rem}
table{border-collapse:collapse;width:100%;margin:.5rem 0}
th,td{border:1px solid #ddd;padding:.4rem .7rem;text-align:left;font-size:.9rem}
th{background:#f6f8fa}
code{background:#f0f0f0;padding:.1rem .3rem;border-radius:3px;font-size:.88em}
pre{background:#f6f8fa;padding:1rem;border-radius:4px;overflow-x:auto}
pre code{background:none;padding:0}
hr{border:none;border-top:1px solid #eee;margin:1.5rem 0}
</style>
</head>
<body>
`)
	buf.WriteString(RenderFragment(md))
	buf.WriteString("</body></html>")
	return buf.String()
}

// RenderFragment converts markdown to an HTML body fragment (no document
// wrapper). Used by the desktop Docs preview so the in-app preview matches the
// exported docs — same converter, one markdown implementation.
func RenderFragment(md string) string {
	var buf bytes.Buffer
	for _, line := range strings.Split(md, "\n") {
		buf.WriteString(mdLineToHTML(line) + "\n")
	}
	return buf.String()
}

func mdLineToHTML(line string) string {
	switch {
	case strings.HasPrefix(line, "# "):
		return "<h1>" + html.EscapeString(line[2:]) + "</h1>"
	case strings.HasPrefix(line, "## "):
		return "<h2>" + html.EscapeString(line[3:]) + "</h2>"
	case strings.HasPrefix(line, "### "):
		return "<h3>" + html.EscapeString(line[4:]) + "</h3>"
	case line == "---":
		return "<hr>"
	case strings.HasPrefix(line, "```"):
		lang := strings.TrimPrefix(line, "```")
		if lang == "" {
			return "</code></pre>"
		}
		return "<pre><code class=\"language-" + html.EscapeString(lang) + "\">"
	case strings.HasPrefix(line, "| "):
		return mdTableRowToHTML(line)
	case strings.HasPrefix(line, "|---|"):
		return "" // skip separator rows
	case line == "":
		return "<br>"
	default:
		return "<p>" + mdInlineToHTML(line) + "</p>"
	}
}

func mdTableRowToHTML(line string) string {
	cells := strings.Split(strings.Trim(line, "| "), " | ")
	var buf strings.Builder
	buf.WriteString("<tr>")
	for _, c := range cells {
		buf.WriteString("<td>" + mdInlineToHTML(strings.TrimSpace(c)) + "</td>")
	}
	buf.WriteString("</tr>")
	return buf.String()
}

var (
	boldRe   = regexp.MustCompile(`\*\*([^*]+)\*\*`)
	italicRe = regexp.MustCompile(`\*([^*]+)\*`)
)

// emphasis applies **bold** and *italic* on already-escaped text. Bold runs
// first so its <strong> wrapper hides the inner text from the italic pass.
func emphasis(s string) string {
	s = boldRe.ReplaceAllString(s, "<strong>$1</strong>")
	s = italicRe.ReplaceAllString(s, "<em>$1</em>")
	return s
}

func mdInlineToHTML(s string) string {
	// Convert `code` spans, escape HTML, then apply bold/italic to non-code text.
	var buf strings.Builder
	for {
		start := strings.Index(s, "`")
		if start < 0 {
			buf.WriteString(emphasis(html.EscapeString(s)))
			break
		}
		buf.WriteString(emphasis(html.EscapeString(s[:start])))
		end := strings.Index(s[start+1:], "`")
		if end < 0 {
			buf.WriteString(emphasis(html.EscapeString(s[start:])))
			break
		}
		end += start + 1
		buf.WriteString("<code>" + html.EscapeString(s[start+1:end]) + "</code>")
		s = s[end+1:]
	}
	return buf.String()
}
